---
- name: Copy backend folder to EC2 server
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Unzip the artifact
  shell: |
    cd /home/ubuntu/
    mkdir backend
    tar -xf backend.tar.gz -C backend

- name: Starting the app
  shell: |
    cd /home/ubuntu/backend
    sudo npm install
    sudo npm run build
    sudo pm2 start npm --name backend -- start
